name: Run ID Command

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-id:
    runs-on: ubuntu-latest

    steps:
    - name: Run ID command
      run: id
